
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Aug 16 04:32:03 CEST 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 48;
  public static final int CONST = 7;
  public static final int RC_BRACE = 4;
  public static final int EQUALS = 25;
  public static final int PLUS_ASSIGN = 42;
  public static final int L_PAREN = 12;
  public static final int GREATER = 29;
  public static final int SEMI = 5;
  public static final int CONTINUE = 19;
  public static final int R_PAREN = 11;
  public static final int LESS = 27;
  public static final int FOR = 17;
  public static final int MINUS = 31;
  public static final int AND = 38;
  public static final int OR = 37;
  public static final int BOOL = 49;
  public static final int COMMA = 6;
  public static final int INC = 21;
  public static final int DIV = 33;
  public static final int PLUS = 32;
  public static final int GREATER_EQUALS = 30;
  public static final int IF = 13;
  public static final int DOT = 24;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int EQUAL = 23;
  public static final int NEW = 36;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 34;
  public static final int NUMBER = 47;
  public static final int MOD = 35;
  public static final int IDENT = 46;
  public static final int BREAK = 18;
  public static final int LC_BRACE = 3;
  public static final int VOID = 10;
  public static final int DIV_ASSIGN = 41;
  public static final int MOD_ASSIGN = 39;
  public static final int COLON = 45;
  public static final int FOREACH = 44;
  public static final int L_BRACE = 8;
  public static final int ELSE = 14;
  public static final int R_BRACE = 9;
  public static final int LESS_EQUALS = 28;
  public static final int READ = 15;
  public static final int NOT_EQUALS = 26;
  public static final int MUL_ASSIGN = 40;
  public static final int DEC = 22;
  public static final int MINUS_ASSIGN = 43;
  public static final int PRINT = 16;
}

