
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 04 16:34:30 CEST 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 49;
  public static final int CONST = 7;
  public static final int RC_BRACE = 4;
  public static final int EQUALS = 26;
  public static final int PLUS_ASSIGN = 43;
  public static final int L_PAREN = 13;
  public static final int GREATER = 30;
  public static final int SEMI = 5;
  public static final int CONTINUE = 20;
  public static final int R_PAREN = 12;
  public static final int LESS = 28;
  public static final int FOR = 18;
  public static final int MINUS = 32;
  public static final int AND = 39;
  public static final int OR = 38;
  public static final int BOOL = 50;
  public static final int COMMA = 6;
  public static final int CLASS = 8;
  public static final int INC = 22;
  public static final int DIV = 34;
  public static final int PLUS = 33;
  public static final int GREATER_EQUALS = 31;
  public static final int IF = 14;
  public static final int DOT = 25;
  public static final int EOF = 0;
  public static final int RETURN = 21;
  public static final int EQUAL = 24;
  public static final int NEW = 37;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 35;
  public static final int NUMBER = 48;
  public static final int MOD = 36;
  public static final int IDENT = 47;
  public static final int BREAK = 19;
  public static final int LC_BRACE = 3;
  public static final int VOID = 11;
  public static final int DIV_ASSIGN = 42;
  public static final int MOD_ASSIGN = 40;
  public static final int COLON = 46;
  public static final int FOREACH = 45;
  public static final int L_BRACE = 9;
  public static final int ELSE = 15;
  public static final int R_BRACE = 10;
  public static final int LESS_EQUALS = 29;
  public static final int READ = 16;
  public static final int NOT_EQUALS = 27;
  public static final int MUL_ASSIGN = 41;
  public static final int DEC = 23;
  public static final int MINUS_ASSIGN = 44;
  public static final int PRINT = 17;
}

